# Generated by Django 2.2.5 on 2023-01-30 03:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('VegasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegasNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField()),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('city', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'VegasNews',
            },
            managers=[
                ('VegasNews', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='temperature',
        ),
    ]
